TASKS = ['Tok', 'Sentences', 'UPOS', 'UFeats', 'Lemmas', 'Dep']

#might be changed for a dict
LGGE =  ['Abaza',
         'Afrikaans',
         'Akkadian',
         'Akuntsu',
         'Albanian',
         'Amharic',
         'Ancient Greek',
         'Ancient Hebrew',
         'Apurina',
         'Arabic',
         'Armenian',
         'Assyrian',
         'Bambara',
         'Basque',
         'Beja',
         'Belarusian',
         'Bengali',
         'Bhojpuri',
         'Bororo',
         'Breton',
         'Bulgarian',
         'Buryat',
         'Cantonese',
         'Catalan',*
         'Cebuano',
         'Chinese',
         'Chukchi',
         'Classical Chinese',
         'Coptic',
         'Croatian',
         'Czech',
         'Danish',
         'Dutch',
         'English',
         'Erzya',
         'Estonian',
         'Faroese',
         'Finnish',
         'French',
         'Frisian Dutch',
         'Galician',
         'German',
         'Gheg',
         'Gothic',
         'Greek',
         'Guajajara',
         'Guarani',
         'Hebrew',
         'Hindi',
         'Hittite',
         'Hungarian',
         'Icelandic',
         'Indonesian',
         'Irish',
         'Italian',
         'Japanese',
         'Javanese',
         'Kaapor',
         'Kangri',
         'Karelian',
         'Karo',
         'Kazakh',
         'Khunsari',
         'Kiche',
         'Komi Permyak',
         'Komi Zyrian',
         'Korean',
         'Kurmanji',
         'Kyrgyz',
         'Latin',
         'Latvian',
         'Ligurian',
         'Lithuanian',
         'Livvi',
         'Low Saxon',
         'Madi',
         'Maghrebi Arabic French',
         'Makurap',
         'Malayalam',
         'Maltese',
         'Manx',
         'Marathi',
         'Mbya Guarani',
         'Moksha',
         'Munduruku',
         'Naija',
         'Nayini',
         'Neapolitan',
         'Nheengatu',
         'North Sami',
         'Norwegian',
         'Old Church Slavonic',
         'Old East Slavic',
         'Old French',
         'Old Irish',
         'Old Turkish',
         'Persian',
         'Polish',
         'Pomak',
         'Portuguese',
         'Romanian',
         'Russian',
         'Sanskrit',
         'Scottish Gaelic',
         'Serbian',
         'Sinhala',
         'Skolt Sami',
         'Slovak',
         'Slovenian',
         'Soi',
         'South Levantine Arabic',
         'Spanish',
         'Swedish',
         'Swedish Sign Language',
         'Swiss German',
         'Tagalog',
         'Tamil',
         'Tatar',
         'Teko',
         'Telugu',
         'Thai',
         'Tupinamba',
         'Turkish',
         'Turkish German',
         'Ukrainian',
         'Umbrian',
         'Upper Sorbian',
         'Urdu',
         'Uyghur',
         'Vietnamese',
         'Warlpiri',
         'Welsh',
         'Western Armenian',
         'Western S.P. Nahuatl',
         'Wolof',
         'Xavante',
         'Xibe',
         'Yakut',
         'Yoruba',
         'Yupik',
         'Zaar']
